### ISSUE TITLE
Shadowing introduced without explanation

### ISSUE THREAD

**Issue by dbp** [data-centric-computing/dcic-public#1]
### Contact Details

dbp@dbpmail.net

### What's your suggestion?

(I'm not sure if this is the right venue for this, as it seems pretty spare; apologies if not!).

I was reading through the book, and noticed that the exercise in https://dcic-world.org/2021-08-21/Naming_Values.html that prompts the reader to try redefining a binding says "How does Pyret respond? What does this tell you about the directory?". The (current) error on CPO is "The declaration of x shadows a previous declaration of x" -- where the term "shadow" doesn't appear in the text (at least on that page) and is not necessarily obviously connected to the "Directory" notion. Probably, from context, a student could figure it out, but not having to figure out jargon from context seems to be a goal, so I thought I'd report this.

I'm not sure if this is actually an issue with the error message (which could describe what shadowing is, rather than just use the jargon), or of the text (which could explain the term).

**Comment by kfisler** [comment]
Great catch, thanks. I've added some explanatory text after that early exercise, with a fwd ref to where we do deal with the issue. 

The update will appear with the upcoming release.
