### ISSUE TITLE
[DCIC Web Page]: typos

### ISSUE THREAD

**Issue by sorawee** [data-centric-computing/dcic-public#10]
### Contact Details

sorawee.pwase@gmail.com

### Which Web page has the problem?

https://dcic-world.org/2021-08-21/part_state.html

### What's the problem?

- A stray close bracket in https://dcic-world.org/2021-08-21/part_state.html#%28part._.Modifying_.Variables_in_.Memory%29,  just before "This process continues: Python advances num to the next list element" 
- A stray close brace in https://dcic-world.org/2021-08-21/part_state.html#%28part._.Writing_.Functions_that_.Modify_.Variables%29, just before "If this function were the only code in your file"
- "Tthere actually are ways to use values" at the end of the page
- "`look up _hash_ methods in Python`" at the end of the page (should be `__hash__`)

### What browser are you seeing the problem on?

Firefox

**Comment by kfisler** [comment]
Fixed. Will appear in next release
