### ISSUE TITLE
[DCIC Web Page]: Python linting

### ISSUE THREAD

**Issue by sorawee** [data-centric-computing/dcic-public#11]
### Contact Details

sorawee.pwase@gmail.com

### Which Web page are you commenting on?

https://dcic-world.org/2021-08-21/part_state.html

### What's your suggestion?

Students might use an IDE with a linting capability. Some non-standard use of Python might cause errors/warnings.

- Docstring should be triple double quotes. The book sometimes uses triple single quotes / single double quote.
- Comments are sometimes written with string literals (see e.g. https://dcic-world.org/2021-08-21/part_state.html#%28part._.The_.Internal_.Structure_of_a_.Test_.Function%29), which might raise warnings about unused expressions.

**Comment by kfisler** [comment]
fixed (and thanks!). will appear in next release
