### ISSUE TITLE
[DCIC Web Page]: Python annotation is not checked

### ISSUE THREAD

**Issue by sorawee** [data-centric-computing/dcic-public#12]
### Contact Details

sorawee.pwase@gmail.com

### Which Web page are you commenting on?

https://dcic-world.org/2021-08-21/part_state.html

### What's your suggestion?

In Python, annotations are not checked without external tools. This is different from Pyret, so an explicit explanation might be warranted.

**Comment by kfisler** [comment]
fixed. will appear in next release
