### ISSUE TITLE
[DCIC]: what about book issues?

### ISSUE THREAD

**Issue by shriram** [data-centric-computing/dcic-public#14]
### Contact Details

shriram@gmail.com

### What's your suggestion?

https://github.com/data-centric-computing/dcic-public/issues/new/choose does not include "issue with book", which is probably the most common kind. That should probably be the top option. Any reason not to have that?

**Comment by kfisler** [comment]
I agree from a labeling standpoint. That said, I would still want the webpage corresponding to the book chapter -- that is helpful for me in identifying which scrbl file I need to open for the editing. Should we maybe just rename the "Webpage problem" form to say "Webpage or book text problem", then have the description indicate to use it for problems with the text or a specific section?

**Comment by shriram** [comment]
I think the Web is just the current presentation; the book is the semantic content. So I think there should be a clear label for issues with the BOOK. That can ask people for the Web URL, chapter number, etc., etc., whatever is needed to figure out where in the book they are referring.

One could also imagine separating Book issues from Web issues: eg, something to do with formatting, color, cookies, etc.

**Comment by debanjan16** [comment]
I agree with @shriram here. Web issues are displaying issues. I was wondering where to put the typo issue. Typo issue clearly goes under issue with the book content.

**Comment by kfisler** [comment]
Fine with me. I'm assuming whoever set up the issue tracker will make the
new category for book issues. Just ask for the page url as we do for web
issues.

**Comment by shriram** [comment]
@kfisler Please check https://github.com/data-centric-computing/dcic-public/issues/new/choose and let me know if you want to see any changes.

**Comment by kfisler** [comment]
Do we need to ask about the browser version for a book issue? Or is that
precautionary as some web issues might get reported as book issues?

Other than that, LGTM

**Comment by shriram** [comment]
It's an optional field and doesn't hurt. You never know. It could be a rendering issue that is presented as a typo, and the rendering could be a function of the browser.
