### ISSUE TITLE
Typo in section 26.5

### ISSUE THREAD

**Issue by debanjan16** [data-centric-computing/dcic-public#15]
### Contact Details

senguptadebanjan16@gmail.com

### Which Web page are you commenting on?

https://dcic-world.org/2021-08-21/part_state.html#%28part._.The_.Many_.Roles_of_.Variables%29

### What's your suggestion?

1. Tracking progress of a computation (e.g., the running value of a result in a for-loop

Missing closing parenthesis.

**Comment by kfisler** [comment]
fixed -- will appear in next release
