### ISSUE TITLE
[DCIC B]: number of examples doesn’t match

### ISSUE THREAD

**Issue by DavidCooperWCU** [data-centric-computing/dcic-public#18]
### Contact Details

@DavidCooperWCU on discord server

### Which Web page has the problem?

https://dcic-world.org/2021-08-21/part_state.html#%28part._.Modifications_to_.Shared_.Data%29

### What's the problem?

in the below section, there are two cases, not three.  Consider changing *all three* to *both* and *each* to *either*.

> With what we have learned, we might have written either of the following two commands:

```
call1 = ToDoItem("call Tina", date(2020, 11, 19), ["urgent"])
call1.descr = "call Tina"
```

> In all *three* cases, the resulting program directory now associates call1 with a call to Tina. The first one creates an entirely new ToDoItem and modifies the value of call1 to this new item. The second one modifes a field within the existing ToDoItem. The same value prints out in *each* case, so the difference doesn’t seem important.

**Comment by kfisler** [comment]
fixed -- will appear in next release
