### ISSUE TITLE
[DCIC Book]: Typo at 24.3 Writing Functions that Modify Variables

### ISSUE THREAD

**Issue by debanjan16** [data-centric-computing/dcic-public#20]
### Contact Details

senguptadebanjan16@gmail.com

### Which Web page has the problem?

https://dcic-world.org/2021-08-21/part_state.html#%28part._.Writing_.Functions_that_.Modify_.Variables%29

### What's the problem?

Stray closing curly brace '}' at the end of the first function definition cast_vote

### What browser are you seeing the problem on?

Chrome

**Comment by kfisler** [comment]
Fixed. Will appear in next release.
