### ISSUE TITLE
[DCIC Book]: Definition of is-winter table predicate inconsistent with later text

### ISSUE THREAD

**Issue by graememcc** [data-centric-computing/dcic-public#28]
### Contact Details

dcic-bugreport@graeme-online.co.uk

### Which Web page has the problem?

https://dcic-world.org/2022-01-25/intro-tabular-data.html#%28part._.Functions_over_.Rows%29

### What's the problem?

Section 7.2 introduces the `shuttle` table, with rows for `Jan`, `Feb`, `Mar` and `Apr`.

The first exercise in section 7.3 asks the student to define an `is-winter` predicate to return true for rows with a month of `Jan`, `Feb` or `Mar`. By this definition, all but the `Apr` row in `shuttle` would match - three rows.

The final paragraph in 7.4.1, and the example sorting output early in section 7.4.2 imply that filtering `shuttle` on `is-winter` would return only two rows - looks like it is using a definition where `Mar` is excluded.

### What browser are you seeing the problem on?

Firefox

**Comment by kfisler** [comment]
Fixed (and thanks for the careful read!). It will appear in a release later this weekend.
