### ISSUE TITLE
[DCIC Book]: Minor typos in Chapter 31

### ISSUE THREAD

**Issue by graememcc** [data-centric-computing/dcic-public#29]
### Contact Details

dcic-bugreport@graeme-online.co.uk

### Which Web page has the problem?

https://dcic-world.org/2022-01-25/part_appendix.html#%28part._htdp-vs-dcic%29

### What's the problem?

**Mismatched parens**
The second bullet point in this section ("Both are built around languages...") has an opening parenthesis at "(in a way Python does not...". This paren is never closed.

**Omitted word**

> DCIC has a lot algorithmic content

is missing the word "of".

### What browser are you seeing the problem on?

Firefox

**Comment by kfisler** [comment]
Fixed (thanks!). Will appear in a release later this weekend.
