### ISSUE TITLE
[DCIC Book]: typo

### ISSUE THREAD

**Issue by fkoksal** [data-centric-computing/dcic-public#31]
### Contact Details

fatihkoksal@gmail.com

### Which Web page has the problem?

https://dcic-world.org/2022-01-25/getting-started.html#%28part._expressions-terminology%29

### What's the problem?

> Value: a expression that can’t be computed further (it is its own result)

Should be `an expression`.

### What browser are you seeing the problem on?

Chrome

**Comment by kfisler** [comment]
Fixed (thanks). Will appear in release later this weekend.
