### ISSUE TITLE
[DCIC Book]: possible missing word in section 31

### ISSUE THREAD

**Issue by gregshubert** [data-centric-computing/dcic-public#32]
### Contact Details

greg.shubert@comcast.net

### Which Web page has the problem?

https://dcic-world.org/2022-01-25/part_appendix.html#%28part._htdp-vs-dcic%29

### What's the problem?

The first sentence at the third bullet point, "The most obvious is that DCIC is in Pyret. HtDP has tons of good ideas, all ignored because it Racket, whose syntax some people (especially some educators) dislike." seems to be missing a word around "because it Racket". Perhaps you meant to add a word like "used"?

"The most obvious is that DCIC is in Pyret. HtDP has tons of good ideas, all ignored because it used Racket, whose syntax some people (especially some educators) dislike."

### What browser are you seeing the problem on?

Firefox

**Comment by kfisler** [comment]
Fixed (thanks!). Will appear in release later this weekend
