### ISSUE TITLE
[DCIC Book]: A small typo in section 1.6; 3rd paragraph, 1st sentence.

### ISSUE THREAD

**Issue by athayworth** [data-centric-computing/dcic-public#33]
### Contact Details

athayworth@gmail.com

### Which Web page has the problem?

https://dcic-world.org/2022-01-25/part_intro.html#%28part._book-style%29

### What's the problem?

In section 1.6, **The Structure of This Book**, there is a small typo in the third paragraph, first sentence, wherein the word highlight is misspelled as "higlight". 

The sentence as-is reads: "We use visual formatting to higlight some of these points."

Hope this helps!

<img width="743" alt="Screen Shot 2022-03-06 at 7 57 32 PM" src="https://user-images.githubusercontent.com/12772562/156950757-14fc76e0-3428-41b3-a4ec-408e91eb4003.png">
 

### What browser are you seeing the problem on?

Brave

**Comment by kfisler** [comment]
Fixed (and thanks!). Will appear in release later this weekend.
