### ISSUE TITLE
[DCIC Book]: online code editor mentoin

### ISSUE THREAD

**Issue by evelynmitchell** [data-centric-computing/dcic-public#34]
### Contact Details

Sorry, I didn't realize my email would be made public.

### Which Web page are you commenting on?

https://dcic-world.org/2022-01-25/getting-started.html

### What's your suggestion?

The reference to the online code editor is not prominent.
"Go to [the on-line editor](https://code.pyret.org/editor) (which we’ll henceforth refer to as “CPO”). For now, we will work only in the right-hand side (the interactions pane)."

It's within a section called Numbers.

The online editor is not mentioned in the section of the Introduction "What makes this book Unique", nor does it have a section to itself called "Online editor".

For people using this text from mobile phones, having access to an online REPL is the difference between reading and learning. I think it should be easier to know it's there and to find.

**Comment by kfisler** [comment]
Thanks for the suggestion (and sorry it took so long for me to get to this). I've added a paragraph in the intro section on programming language choices about editors. This includes a link to CPO.
