### ISSUE TITLE
[DCIC Book]: error

### ISSUE THREAD

**Issue by shriram** [data-centric-computing/dcic-public#36]
### Contact Details

shriram@gmail.com

### Which Web page has the problem?

https://dcic-world.org/2022-01-25/processing-lists.html#%28part._uniq%29

### What's the problem?

The prose after `uniq-rec2` says that the program has a tail call, but that's clearly not right, because right after the call is the conditional. I'm not sure what this was *meant* to say or whether it was talking about some other version, but what's there is simply false.

**Comment by kfisler** [comment]
I removed the offending paragraph.
