### ISSUE TITLE
[DCIC Book]: Opening parenthesis missing in example

### ISSUE THREAD

**Issue by kishvanchee** [data-centric-computing/dcic-public#39]
### Which Web page has the problem?

https://dcic-world.org/2022-01-25/processing-lists.html#%28part._str-len-eg-code%29

### What's the problem?

Missing `[` in example

![Screenshot_20220629_220557-1](https://user-images.githubusercontent.com/24776049/176489732-9a24b4c5-0bbb-4ed5-b38a-594f5ac2e68d.png)

### What browser are you seeing the problem on?

Firefox

**Comment by kfisler** [comment]
Fixed. Will appear in release this weekend.
