### ISSUE TITLE
[DCIC Web Page]: tiny typos / suggestions

### ISSUE THREAD

**Issue by stchang** [data-centric-computing/dcic-public#4]
### Contact Details

stchang216@gmail.com

### Which Web page has the problem?

https://dcic-world.org/2021-08-21/part_appendix.html

### What's the problem?

Started reading the book (thanks to @dbp) but started at the end:
https://dcic-world.org/2021-08-21/part_appendix.html

here are some tiny typos I noticed (tried to include enough context to make the location unambiguous):
- "variables’ scope" => "variables’ scopes"
- "Pyret have extensive" => "Pyret has extensive"
- "optional mechanism of annotations that were" => "optional mechanism of annotations that was"
- "Python has a complicated table that describes what values are true and which are false" => use the same word? what/which
- "to get between the nodes" => "to go between the nodes"
- "third value’s three bytes" => "third value’s three bits"
- "chacters" => "characters"
- "to be a rich, tree-structured according to some datatype" => "to be rich and tree-structured according to some datatype" (?)

Non-typos
- when discussing space-time tradeoff, mention "dynamic programming" since that is the context where most programmers use it and learn about it (in their algorithms course)

### What browser are you seeing the problem on?

Chrome

**Comment by kfisler** [comment]
Fixed (will appear in next release) with exception of dynamic programming comment which is on the list of ideas to consider.
