### ISSUE TITLE
[DCIC Book]: Section 6.4: Incorrect value in *where* clause

### ISSUE THREAD

**Issue by rawalplawit** [data-centric-computing/dcic-public#40]
### Which Web page has the problem?

https://dcic-world.org/2022-01-25/Conditionals_and_Booleans.html#%28part._else-if%29

### What's the problem?

In section **6.4 Asking Multiple Questions**, the `add-shipping` function at the end has incorrect where clause.

Example
```pyret
fun add-shipping(order-amt :: Number) -> Number:
 ....
where:
  add-shipping(10) is 10 + 4
  add-shipping(3.95) is 3.95 + 4
  add-shipping(20) is 20 + 8
  add-shipping(10.01) is 10.01 + 8
  add-shipping(30) is 30 + 12 <------------- shoud be 30 + 8
end
```

![image](https://user-images.githubusercontent.com/39916917/179777897-27561353-78b0-448d-90a6-ee9b20860f7e.png)

**Comment by kfisler** [comment]
Fixed (thanks!). It will appear in a release later this weekend.
