### ISSUE TITLE
[DCIC Book]: Typo in 8.1.4 Normalization, Systematically

### ISSUE THREAD

**Issue by rawalplawit** [data-centric-computing/dcic-public#41]
### Which Web page has the problem?

https://dcic-world.org/2022-01-25/processing-tables.html#%28part._.Normalization__.Systematically%29

### What's the problem?

![image](https://user-images.githubusercontent.com/39916917/180442989-757cb5b6-a03c-44a4-b972-6fcc2f8da481.png)

**Comment by kfisler** [comment]
Fixed (thanks!). Will appear in a release later this weekend.
