### ISSUE TITLE
[DCIC Book]: Typo in Section 1.7

### ISSUE THREAD

**Issue by ar9v** [data-centric-computing/dcic-public#43]
### Contact Details

aricav96@gmail.com

### Which Web page has the problem?

https://dcic-world.org/2022-08-28/part_intro.html#%28part._.Organization_of_the_.Material%29

### What's the problem?

In the third item, `Programming with State`, the last sentence reads: `The notional machine in this section separate the naming environment (here called the directory) from a heap of structured data values.` 

I think you may mean:
- The notional **machines** in this section separate the naming environment (here called the directory) from a heap of structured data values.
- The notional machine in this section **separates** the naming environment (here called the directory) from a heap of structured data values.

### What browser are you seeing the problem on?

Firefox

**Comment by kfisler** [comment]
Fixed and will appear in upcoming release. Thanks!
