### ISSUE TITLE
[DCIC Book]: Mistake in contract of List.member

### ISSUE THREAD

**Issue by timotree3** [data-centric-computing/dcic-public#45]
### Which Web page has the problem?

https://dcic-world.org/2022-08-28/tables-to-lists.html

### What's the problem?

Thanks for this book! I teach programming, and I really like your approach. There is a mistake in this paragraph

![image](https://user-images.githubusercontent.com/6473438/196059208-8fd47442-5f39-4247-a8c1-d5f95f8fc5cb.png)

The type given is `member :: (A -> Boolean), Any -> Boolean`, but the [function is actually](https://www.pyret.org/docs/latest/lists.html#%28part._lists_member%29) `member :: (lst :: List<a>, elt :: a) -> Boolean`. If the point is to teach `Any`, I think you'll have to find a different function as an example.

### What browser are you seeing the problem on?

Firefox

**Comment by shriram** [comment]
Good point, thanks. We'll have to think this through a bit.

[NB: We tend to just let bug reports pile up over the course of the semester, while we're teaching, and then deal with them during break.]

**Comment by kfisler** [comment]
Actually, `Any` is the supported type, both in the library of list functions that is in use at this point and in the built-in `member` function. Looks to me that the Pyret documentation is where the error lies here.

I've fixed the contract in the text to have a list as the first argument and will file a separate issue regarding the type of member in the Pyret docs.
