### ISSUE TITLE
[DCIC Book]: Small markup mistake

### ISSUE THREAD

**Issue by timotree3** [data-centric-computing/dcic-public#46]
### Which Web page has the problem?

https://dcic-world.org/2022-08-28/partial-domains.html

### What's the problem?

Here it looks like "can't" is being interpreted as an inline code block `can't`. I'm guessing the intention was emphasis "*can't*"

![image](https://user-images.githubusercontent.com/6473438/196059971-3c6a99ac-a9db-453e-8952-78896ec09701.png)

### What browser are you seeing the problem on?

Firefox

**Comment by shriram** [comment]
Doh! Thanks for the catch!
