### ISSUE TITLE
[DCIC Book]:”dictionary” should be “directory”

### ISSUE THREAD

**Issue by DavidCooperWCU** [data-centric-computing/dcic-public#47]
### Contact Details

dcooper@wcupa.edu

### Which Web page has the problem?

https://dcic-world.org/2022-08-28/Naming_Values.html#%28part._.Understanding_the_.Run_.Button%29

### What's the problem?

In the paragraph below, *dictionary* is used when talking about the *directory*.

> Now, the two-shape image would be in the directory, associated with the name two-rects. The purple rectangle by itself, however, still would not be stored in the **dictionary**. We could, however, reference the two-shape image by name, as shown below:

### What browser are you seeing the problem on?

Safari

**Comment by kfisler** [comment]
Fixed and will appear in the next release. Thanks!
