### ISSUE TITLE
[DCIC Book]: 24.4 test function code should have "theVotes" instead of "cast_vote"

### ISSUE THREAD

**Issue by jonathanzhou1** [data-centric-computing/dcic-public#48]
### Contact Details

jonathan_zhou@brown.edu

### Which Web page has the problem?

https://dcic-world.org/2021-08-21/part_state.html#%28part._intro-python%29

### What's the problem?

![image](https://user-images.githubusercontent.com/70667576/211229631-88cedaac-7e20-464e-b965-15ca0be265b6.png)

![image](https://user-images.githubusercontent.com/70667576/211229654-c8ba8779-be22-433e-90e9-e9d6a4cc84ae.png)

For these two 'test_cast_vote' functions, I think the first 'assert' line should be:

`assert "basbousa" in theVotes`,
not
`assert "basbousa" in cast_vote`

### What browser are you seeing the problem on?

Chrome

**Comment by kfisler** [comment]
This section has been redesigned and this example is no longer included.
