### ISSUE TITLE
[DCIC Book]: 25.2 "Do Now" order for calls is flipped

### ISSUE THREAD

**Issue by jonathanzhou1** [data-centric-computing/dcic-public#49]
### Contact Details

jonathan_zhou@brown.edu

### Which Web page has the problem?

https://dcic-world.org/2021-08-21/part_state.html#%28part._intro-python%29

### What's the problem?

![image](https://user-images.githubusercontent.com/70667576/211229817-1d79ee3e-296e-49d2-bc61-16d41a30f514.png)

The `call2 = call3` in the paragraph should be `call3 = call2`

### What browser are you seeing the problem on?

Chrome

**Comment by kfisler** [comment]
This section has been redesigned and the error does not appear in the new section.
