### ISSUE TITLE
[DCIC Book]: 25.1 Incorrect date field

### ISSUE THREAD

**Issue by jonathanzhou1** [data-centric-computing/dcic-public#50]
### Contact Details

jonathan_zhou@brown.edu

### Which Web page has the problem?

https://dcic-world.org/2021-08-21/part_state.html#%28part._intro-python%29

### What's the problem?

![image](https://user-images.githubusercontent.com/70667576/211230756-c12dbbe5-2117-4fff-a94a-9840ee8667af.png)

`milk_item.due = date(11, 15, 2020)` should be:
`milk_item.due = date(2020, 11, 15)`

### What browser are you seeing the problem on?

Chrome

**Comment by kfisler** [comment]
Fixed and will appear in next release.
