### ISSUE TITLE
[DCIC Book]: Slight spelling typo

### ISSUE THREAD

**Issue by jonathanzhou1** [data-centric-computing/dcic-public#51]
### Contact Details

jonathan_zhou@brown.edu

### Which Web page has the problem?

https://dcic-world.org/2021-08-21/part_state.html#%28part._modifying-data-equality%29

### What's the problem?

![image](https://user-images.githubusercontent.com/70667576/211714905-00e53bdf-0ec4-472a-aff0-76aa034c20ad.png)

Just an extra 't' in the first word in the aside box.

### What browser are you seeing the problem on?

Chrome

**Comment by kfisler** [comment]
Thanks for reporting this. Fixed as part of our round of updates.
