### ISSUE TITLE
[DCIC Book]: splice the appendices

### ISSUE THREAD

**Issue by sorawee** [data-centric-computing/dcic-public#60]
### Contact Details

sorawee.pwase@gmail.com

### Which Web page are you commenting on?

https://dcic-world.org/2023-02-21/booklet_appendices.html

### What's your suggestion?

The "Appendices" section is the only section in the "Appendices" chapter (and it looks like there won't be any other sections in the chapter). The suggestion is to splice the content of the "Appendices" section out (i.e. promoting its subsections to sections). This removes the redundancy in the organization and leads to an easier web navigation.

**Comment by shriram** [comment]
Yeah, there are a few others like this too. Mostly this is is just the pain of wrangling with Scribble…

**Comment by shriram** [comment]
Pushed fix in 57e6461c838e39f0472082952a1127ffad354e0d
