### ISSUE TITLE
[DCIC Book]: Minor typo on booklet intro (FIX: ". this corresponds" → ". This corresponds")

### ISSUE THREAD

**Issue by Nathansbud** [data-centric-computing/dcic-public#61]
### Which Web page has the problem?

https://dcic-world.org/…

### What's the problem?

Mentioned in the title, but ". this corresponds" (in the section about CS19) should be capitalized.

### What browser are you seeing the problem on?

Chrome

**Comment by kfisler** [comment]
Fixed, thanks. Apologies for the delay.

**Comment by kfisler** [comment]
eb3c2dbdfa41e48f89fba17dcf9e590298bce39b
