### ISSUE TITLE
problem with reference to table in paragraph number 8.1

### ISSUE THREAD

**Issue by peter-goof** [data-centric-computing/dcic-public#62]
### Contact Details

borshch-pm@mail.ru

### Which Web page has the problem?

https://code.pyret.org/editor#program=1pR-HSaA7LfxIEgTY2iwl_tST7HxYFzSQ

### What's the problem?

include gdrive-sheets
ssid = "1YOBbAv1kHRS6SZQ-OtbyYQ3fV6l7fsyubN_J856i_sI"
event-data = 
  load-table: name,email,tickcount,discount,delivery
    source: load-spreadsheet(ssid).sheet-by-name("Лист1",true)
  end
mistake:No Spreadsheet with id "1YOBbAv1kHRS6SZQ-OtbyYQ3fV6l7fsyubN_J856i_sI" found
with the table specified by the authors in the book, everything works, but does not work with my table
What do I need to do to make my link also work?

**Comment by kfisler** [comment]
file link doesn't work and this is nearly a year old (my bad there), so just closing at this point

**Comment by peter-goof** [comment]
thank you
