### ISSUE TITLE
[DCIC Book]: 26.5.3 refers to `big-bang` which doesn't exist

### ISSUE THREAD

**Issue by timotree3** [data-centric-computing/dcic-public#63]
### Which Web page has the problem?

https://dcic-world.org/2023-02-21/games-reactive.html#(part._.Version__.Descending)

### What's the problem?

It says
> Actually, we’re forgetting one small thing: the initial World State given to `big-bang`!

There is no other reference to `big-bang` on the page. I believe that this is left over from a Racket version of the text and that the corresponding concept in Pyret is a `reactor` definition

**Comment by kfisler** [comment]
commit 269782b1c9d640e3d36bdc4217f1ca9889030b1b

**Comment by kfisler** [comment]
Fixed, thanks!
