### ISSUE TITLE
[DCIC Book]: unclear exercise text

### ISSUE THREAD

**Issue by gsinclair** [data-centric-computing/dcic-public#64]
### Contact Details

gsinclair@gmail.com

### Which Web page has the problem?

https://dcic-world.org/2023-02-21/getting-started.html

### What's the problem?

`the max of 5 - 10 and -20`

It is not clear what is meant by this exercise.

### What browser are you seeing the problem on?

iPad safari

**Comment by kfisler** [comment]
wording adjusted. Thanks for reporting, and sorry for the delayed handling.

**Comment by kfisler** [comment]
eb3c2dbdfa41e48f89fba17dcf9e590298bce39b
