### ISSUE TITLE
[DCIC Web Page]: Use <a rel="next"> and <a rel="prev"> on existing 'next' and 'prev' links

### ISSUE THREAD

**Issue by harinath** [data-centric-computing/dcic-public#69]
### Which Web page are you commenting on?

https://dcic-world.org/2023-02-21/booklet_intro.html

### What's your suggestion?

Please use [HTML sequential links](https://html.spec.whatwg.org/multipage/links.html#sequential-link-types) to link the booklets together.  

This allows me , for instance, on the emacs built-in web "browser" (`M-x eww`), to use `n` and `p` keys to navigate to the next/prev booklet.

**Comment by shriram** [comment]
Thanks for the report. We use Racket Scribble, so this is a bit out of our control (I don't want to fork Scribble just for this). 

I've brought it up on the Scribble boards to see if we can get it fixed there. When Scribble fixes this, we'll automatically inherit the behavior.

Just for that reason, I'm going to close this issue. It's not a #wontfix but rather a "it'll get fixed automatically when the Scribble infrastructure does".

**Comment by shriram** [comment]
Matthew Flatt has committed a change to Scribble that should implement this:

https://github.com/mflatt/scribble/commit/faf92fa8638acfb193f0a14953b9779a31f2cdcd
