### ISSUE TITLE
[DCIC Book]: typo in equality

### ISSUE THREAD

**Issue by shriram** [data-centric-computing/dcic-public#70]
### Contact Details

shriram@gmail.com

### Which Web page has the problem?

https://dcic-world.org/2023-02-21/unified-equality.html

### What's the problem?

"This sequence of examples points out that we seem to be raising three possible notions of equality:"

"three" should be "two".

Credit to Danil Braun.

**Comment by kfisler** [comment]
Fixed

**Comment by kfisler** [comment]
eb3c2dbdfa41e48f89fba17dcf9e590298bce39b
