### ISSUE TITLE
[DCIC Book]: Typo in section 8.2 

### ISSUE THREAD

**Issue by debanjan16** [data-centric-computing/dcic-public#71]
### Which Web page has the problem?

https://dcic-world.org/2023-02-21/queues-from-lists.html#:~:text=We%E2%80%99ve%20see%20elsewhere%20how

### What's the problem?

I think there is a typo in the line "We’ve see elsewhere how "

It should be We will see elsewhere because the reference comes at a much later chapter.

### What browser are you seeing the problem on?

Chrome

**Comment by kfisler** [comment]
Fixed, thanks!

**Comment by kfisler** [comment]
eb3c2dbdfa41e48f89fba17dcf9e590298bce39b
