### ISSUE TITLE
[DCIC Web Page]: spacing improvement

### ISSUE THREAD

**Issue by sorawee** [data-centric-computing/dcic-public#72]
### Contact Details

sorawee.pwase@gmail.com

### Which Web page are you commenting on?

https://dcic-world.org/2023-02-21/processing-lists.html#%28part._running-sum-1st-attempt%29

### What's your suggestion?

`[list: 3,  7, 12]` probably should be `[list: 3, 7, 12]` instead (I don't want to call this a problem. It's a slight typo that causes incorrect formatting, but nothing is wrong per se)

**Comment by kfisler** [comment]
fixed, thanks!

**Comment by kfisler** [comment]
eb3c2dbdfa41e48f89fba17dcf9e590298bce39b
