### ISSUE TITLE
[DCIC Web Page]: navigation bar doesn't display section title with "code" correctly

### ISSUE THREAD

**Issue by sorawee** [data-centric-computing/dcic-public#73]
### Contact Details

sorawee.pwase@gmail.com

### Which Web page has the problem?

https://dcic-world.org/2023-02-21/processing-lists.html#%28part._len-eg%29

### What's the problem?

<img width="202" alt="Screenshot 2023-09-05 at 11 46 40 PM" src="https://github.com/data-centric-computing/dcic-public/assets/9099577/a1363ca0-4bb1-4917-9c9a-5b103cc8ee2e">

The first `my-` should be `my-len`. The second `my-` should be `my-sum`. Etc.

I'm fairly confident this is due to JavaScript in [`hilite.js`](https://dcic-world.org/2023-02-21/hilite.js). 

### What browser are you seeing the problem on?

Firefox

**Comment by kfisler** [comment]
Kathi passing along to Ben, who knows more of the js stuff
