### ISSUE TITLE
[DCIC Book]: failure to use display mode

### ISSUE THREAD

**Issue by shriram** [data-centric-computing/dcic-public#74]
### Which Web page has the problem?

https://dcic-world.org/2022-08-28/partial-domains.html

### What's the problem?

Look for "Again, we’re missing a test. How do we write it?". The code after it should be in display mode, not inline.

**Comment by kfisler** [comment]
fixed

**Comment by kfisler** [comment]
eb3c2dbdfa41e48f89fba17dcf9e590298bce39b
