### ISSUE TITLE
[DCIC Book]: please enter a brief summary here

### ISSUE THREAD

**Issue by 3ZA** [data-centric-computing/dcic-public#75]
### Which Web page has the problem?

https://dcic-world.org/2023-02-21/intro-tabular-data.html

### What's the problem?

In the last part of `4.1.4.3 Adding New Columns`

```
fun compute-wages(r :: Row) -> Number:
  doc: "compute total wages based on wage and hours worked"
  r["hourly-wage"] * r["hours-worked"]
end

build-column(employees, "total-wage", compute-wages)
```
Running the example above results in `The identifier build-column is unbound:`
Instead, it should be employees.build-column("total-wage", compute-wages) as per the pyret [documentation](https://pyret.org/docs/latest/tables.html#%28part._tables_.Table_table_build-column%29).

**Comment by kfisler** [comment]
Thanks for the report, but the original code is fine. The error came from not having loaded the pyret extension file mentioned at the start of the section. The book hasn't introduced objects yet.

**Comment by kfisler** [comment]
eb3c2dbdfa41e48f89fba17dcf9e590298bce39b
