### ISSUE TITLE
[DCIC Book]: A typo in the terminology section

### ISSUE THREAD

**Issue by Rtizer-9** [data-centric-computing/dcic-public#78]
### Which Web page has the problem?

https://dcic-world.org/2023-02-21/getting-started.html#%28part._expressions-terminology%29

### What's the problem?

>**Expression:** a computation written in the formal notation of a programming language
> Examples here include 4, 5 + 1, and (3 + 4) * (5 + 1)

If I understand correctly I think you meant to write 3 + 4 here instead of just 4 because that's a value in this context and not something which can be computed further.

**Comment by kfisler** [comment]
Thanks for reaching out. Actually, values are considered expressions. The
required "computation" is simply to return the value. If we didn't do that,
there would be no minimal case of expressions, which makes it hard to
define them recursively.

Kathi

**Comment by Rtizer-9** [comment]
Oh now I get it, the definition of value itself has expression which clearly means value is a subset of expression.

I think you should have some telegram group/discord/subreddit otherwise people are gonna fill up issues with doubts and not actual issues like these, and I've just started with the book...

Thanks.

**Comment by kfisler** [comment]
We do have a discord channel where you can ask questions.
discord.gg/7aFMB3b6Mt <https://t.co/p9GYmeIyMy>

Kathi
