### ISSUE TITLE
[DCIC]: Sudden introduction of 'fold' in Ch 17.3

### ISSUE THREAD

**Issue by debanjan16** [data-centric-computing/dcic-public#9]
### Contact Details

senguptadebanjan16@gmail.com

### What's your suggestion?

I understand that students in CS19 comes with the knowledge of 'fold' from HtDP and the Algorithms section is not used by CS111. So this discontinuity may not to apparent to the author's eyes. But if I consider DCIC as a standalone book then the readers are suddenly introduced to a HoF called 'fold' while discussing Streams in chapter 17.3. 

In Processing Lists chapter accumulator type functions are covered which is chapter 10. No mention of 'fold' HoF there although map and filter are mentioned many times. Similarly other HoFs are also not covered. This transition may look like a sharp jump for the reader, considering DCIC is a standalone book for first time programmers/CS students.

**Comment by kfisler** [comment]
fixed. will appear in next release
